### ISSUE TITLE
download PDF doesn't work 

### ISSUE THREAD

**Issue by gerhard67** [MicrosoftDocs/azure-reference-other#101]
If I click download PDF I got "We can't open this file / Something went wrong." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c1bd60-1296-3916-576f-7e66406e7e88
* Version Independent ID: 98ce7ef9-48e6-001c-967f-0f0c204e3921
* Content: [Stream Analytics Query Language Reference - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/stream-analytics-query-language-reference#feedback)
* Content Source: [stream-analytics-docs/stream-analytics-query-language-reference.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/stream-analytics-query-language-reference.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by JasonWHowell** [comment]
@gerhard67 Sorry for the delay. We'll look into why the PDFs are working. Thanks for alerting us about the issue.

**Comment by JasonWHowell** [comment]
Thanks for raising the issue @gerhard67 

We have fixed the PDF link and adjusted the site configuration to prevent the problem.

Thanks, Jason

**Comment by JasonWHowell** [comment]
https://docs.microsoft.com/en-us/stream-analytics-query/opbuildpdf/toc.pdf?branch=live
