### ISSUE TITLE
Azure SQL DB Output is not writing with INTO statement.

### ISSUE THREAD

**Issue by muruganbalan** [MicrosoftDocs/azure-reference-other#105]
Hi Team, I am trying to 

1. Get the data from Event Hub (Stream Analytics Input) 
2. Stream Analytics query by selecting specific columns 
3. Write the result back into Azure SQL DB with INTO statement.

But the data is not getting loaded into Azure SQL DB table which already exists. I am not able to debug on this. Tried with all possibilities as per the SQL query reference document.

SELECT name
FROM [src]
[tgt]

Any help would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 310af5df-d9b5-1508-3b47-3c4b37cf1cea
* Version Independent ID: 15b93b2b-b6dc-c4a2-533e-f5b80950c237
* Content: [INTO (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/into-azure-stream-analytics#feedback)
* Content Source: [stream-analytics-docs/into-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/into-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @muruganbalan - I apologize for the delayed response. 

Everything you mentioned should be supported. Have you reviewed [Azure Stream Analytics output to Azure SQL Database](https://docs.microsoft.com/azure/stream-analytics/stream-analytics-sql-output-perf)?

**Comment by JasonWHowell** [comment]
@muruganbalan it looks like Mary has provided a thoughtful page that should cover your question. 

Please let us know if you need anything else. I'll close the thread assuming its resolved, but happy to continue if you need further clarification. Thanks~ Jason
