### ISSUE TITLE
Datetime CAST error

### ISSUE THREAD

**Issue by awoSYS** [MicrosoftDocs/azure-reference-other#107]
When testing a Stream Analytics Query locally, it fails when trying to cast an ISO datetime string to datetime type:
`Cannot cast value '2020-01-06T10:10:343.4589604Z' of type 'nvarchar(max)' to type 'datetime' in expression 'CAST ( [timestamp] AS datetime )`.
Complete Query:
```sql
SELECT 
    COUNT(*) AS eventCount, 
    TopOne() OVER (ORDER BY CAST([timestamp] AS datetime) DESC) AS LastEvent, 
    unitID
  FROM iothub
  GROUP BY unitID, HOPPINGWINDOW(second, 15, 1)
```
Isn't the string in the correct format? When leaving the CAST out, it says that ordering over nvarchar(max) is not possible.

I'm developing with Visual Studio Code on Ubuntu 18.04 LTS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12eb08ab-be52-29e2-e0ff-76727c867c9e
* Version Independent ID: 6849d9fa-653c-701d-d8ac-964e98c5370d
* Content: [CAST (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/cast-azure-stream-analytics)
* Content Source: [stream-analytics-docs/cast-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/cast-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by JasonWHowell** [comment]
@AlexR please take a look when you have a moment. Thanks! Jason

**Comment by mamccrea** [comment]
Hi @awoSYS! You are receiving this error because the value is not a valid datetime. 

`2020-01-06T10:10:343.4589604Z` has 343 seconds, but the seconds place should only have two digits. Removing the extra digit should resolve the error.

**Comment by mamccrea** [comment]
I hope this information was helpful! I will now proceed to close this thread. If you have any additional questions, please reopen the issue.

#please-close
