### ISSUE TITLE
search_condition syntax

### ISSUE THREAD

**Issue by dkatztibco** [MicrosoftDocs/azure-reference-other#108]
does search_condition work against character arguments? I can't get it to. eg having x="sum"
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c929bd42-47b4-d1b2-835a-490faca271bb
* Version Independent ID: 0b2b6cbe-5067-e217-1de0-44973c8baea0
* Content: [HAVING (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/having-azure-stream-analytics?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fstream-analytics%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#feedback)
* Content Source: [stream-analytics-docs/having-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/having-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @dkatztibco - I apologize for the delayed response.

We do support comparisons against strings, but in x="sum" the sum is a column reference since double quotes are used. It should be x = 'sum' to make sum be interpreted as a string.

Hope this helps.

**Comment by JasonWHowell** [comment]
@dkatztibco It looks like Mary has provided a thoughtful answer. Please let us know if you need anything else. I'll close the thread assuming its resolved, but happy to continue if you need further clarification. Thanks~ Jason

**Comment by dkatztibco** [comment]
Thanks! That did it

*David Katz*, TIBCO Data Science


1.541.324.7417
