### ISSUE TITLE
Type mapping for parquet as output is missing

### ISSUE THREAD

**Issue by arashnezami** [MicrosoftDocs/azure-reference-other#109]
Hi, What type mapping have been used for Parquet as output?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593d33f2-cdb5-f4f0-87b7-65f2064684bc
* Version Independent ID: 4fd0c3d0-8cbd-d3e7-20d9-513450d4761a
* Content: [Data Types (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/data-types-azure-stream-analytics#feedback)
* Content Source: [stream-analytics-docs/data-types-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/data-types-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by yitao-zhang** [comment]
- For basic types, the conversion table is like below

ASA type | Parquet Type
-- | --
Bigint | INT64
Float | DOUBLE
nvarchar(max) | BYTE_ARRAY  (annotation: UTF8)
Datetime | INT96

- For the complex ASA types, i.e. Record and Array: they are constructed recursively using the basic data types using the Dremel method:
https://blog.twitter.com/engineering/en_us/a/2013/dremel-made-simple-with-parquet.html
  

- However, we do have a limitation that "**Array of Array**" data type is not supported for now.
 
Thanks

**Comment by JasonWHowell** [comment]
@arashnezami I hope the answer Yitao has provided resolves your question, but please let us know if further clarification is needed. I'll close the issue for now, but circle back if needed.
