### ISSUE TITLE
Is there a limitation on the number of JOIN clauses one can use in a query?

### ISSUE THREAD

**Issue by jjimenezroda** [MicrosoftDocs/azure-reference-other#110]
When using Event Hubs as the source of stream data, I've found that, when my query uses more than 5 JOIN statements, I'm getting hit by the Event Hubs limitation of maximum 5 readers on the same partition. My ASA Job uses a specific Event Hubs partition and we are using the WITH data As.... clause (so only one reader, if I'm not wrong). Nevertheless, when I reduce the amount of JOIN clauses in a single SubQuery, then it works (and I can even add more Subqueries as long as none of them exceeds 5 JOIN clauses).

Is there a limitiation somehow? I could not find any documentation pointing in such direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ef43ed-597c-56f3-7cb6-f42e0b7ea288
* Version Independent ID: 59b37583-46a8-2cf7-495a-e4731af83aa0
* Content: [JOIN (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/join-azure-stream-analytics#feedback)
* Content Source: [stream-analytics-docs/join-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/join-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @jjimenezroda. I apologize for the delayed response.

There is no limitation on joins, but Event hub has a limit on the number of readers (<= 5). Please reference the [Event Hubs Consumer groups](https://docs.microsoft.com/azure/stream-analytics/stream-analytics-define-inputs#event-hubs-consumer-groups) section of the streaming inputs article.

**Comment by JasonWHowell** [comment]
@jjimenezroda Looks like Mary has provided an answer, so I'll close out this issue. Please let us know if you have additional followup needed and we'll reconvene. Thanks~ Jason
