### ISSUE TITLE
Timestamp in thumblingwindow

### ISSUE THREAD

**Issue by cblomart** [MicrosoftDocs/azure-reference-other#111]
In the samples the System.Timestamp() is used to identify the window end.
Unfortunately, it is not always accurate as the job could need to process old data that would still be "bucketed" in the same window.
So practically I see that when the azure function fails and provides bug correction, events are reprocessed but the windowend will be the date when the function was corrected and not the end of the thumbling window.
Is there a way to solve this (or a uservoice)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7481e5ce-9b20-2edb-4d3c-d73858d1dde8
* Version Independent ID: ff6f279d-6469-012a-1e4b-88b6f1830b8e
* Content: [Tumbling Window (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/tumbling-window-azure-stream-analytics)
* Content Source: [stream-analytics-docs/tumbling-window-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/tumbling-window-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by JasonWHowell** [comment]
I discussed this issue with our devs. What's your TIMESTAMP BY clause in the job query?

The “old data” mentioned is being placed on the timeline based on the policies and TIMESTAMP BY, and may or may not belong to the unexpected window. Or may even be dropped if DROP policy is specified.

We don't think this is an issue with windowing or the System.Timestamp(). Both windowing and value of System.Timestamp() are computed based on the timeline the input events are organized into. 

The input events are being organized into a repeatable timeline based on whether there is a TIMESTAMP BY clause and/or ingress properties, like disorder/late arrival  delay and drop/adjust.

**Comment by cblomart** [comment]
I feel that there was some natural misunderstanding upon my first explanation.

Windowing works well as far as I can see.

My problem is with the outputted data where I would like to have the proper window frame times (end here).

To be clear, I have an azure function piping the stream job result to Azure log analytics.
In log analytics, I would like the "timegenerated" to be mapped to the end of the time window.

In my situation, the real timestamp of the event is nested into a JSON object and I use getarrayvalue to get the values. 
As it seems that I can't use the nested value in the "timestamp by" close... there is simply no "timestamp by".

Finally, to get a sense of the time window end I use the System.Timestamp() function as suggested in the doc examples.

What I reason is happening is the following:
* my function fails (because I work on it) so the stream job reprocesses it until my function finally accepts it (i guess there will be a maximum retry or timeout somewhere)
* when the window is reprocessed, the System.Timestamp() will provide the current date and not the "real" time window end. This results in data being sent to Azure logs with the wrong "timegenerated".

Naturally, if my Azure function is working well it won't ever cause a problem. Re-processing fails is still a nice feature of stream analytics and processing them correctly is then a key point.

**Comment by mamccrea** [comment]
When Stream Analytics processes a window, System.Timestamp() is the end of the time window. If Stream Analytics fails to output to your Azure Function, Stream Analytics will continue to try to output. No matter how long Stream Analytics attempts to output to an Azure Function, the System.Timestamp() for that window remains the same. Nothing is reprocessed on the Stream Analytics side, and data stays unchanged until the output succeeds.

Perhaps there is an issue with the way the Azure Function is implemented. For example, maybe the wall clock time keeps progressing during retries and diverges more and more from the System.Timestamp() value. Or if multiple partitions write into the same Azure Function, then different partitions may temporarily diverge in the value of System.Timestamp() as they are processed independently.

**Comment by mamccrea** [comment]
I hope this information has been helpful. I will now proceed to close this issue. If you have any additional questions, please re-open the issue.

#please-close
