### ISSUE TITLE
Queries return null

### ISSUE THREAD

**Issue by qusp66** [MicrosoftDocs/azure-reference-other#114]
Queries such as SELECT GetMetadataPropertyValue(iotInput, 'IoTHub.CorrelationId') AS iotCorrelationId return null even thought the metadata is there. AS shown below using EPH to read from the event hub
Telemetry received:
{"eap":"ad5250314f563104020629"}
Application properties (set by device):
{"tenant":"elux","hubname":"devhub-luca","customerID":"55ae1d7b-63b3-4993-811d-6fdd3b176255","deviceid":"$twins.deviceId"}
System properties (set by IoT Hub):
{"iothub-connection-device-id":"black_python","iothub-connection-auth-method":"{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","iothub-connection-auth-generation-id":"637200287058498882","iothub-enqueuedtime":1584524469296,"iothub-message-source":"Telemetry","x-opt-sequence-number":212482,"x-opt-offset":"17180105624","x-opt-enqueued-time":1584524469382}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f18461c-e0bf-e7b4-f34c-5a632fb06f66
* Version Independent ID: b7e06d15-933e-f361-21dd-e4e2a9294669
* Content: [GetMetadataPropertyValue (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/getmetadatapropertyvalue#feedback)
* Content Source: [stream-analytics-docs/getmetadatapropertyvalue.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/getmetadatapropertyvalue.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @qusp66! Are you getting these results when [testing a query](https://docs.microsoft.com/azure/stream-analytics/stream-analytics-test-query) or when the job is running?

**Comment by mamccrea** [comment]
The value of "System.Timestamp" is the used for blob output path. "System.Timestamp" is normally assigned using the value in "TIMESTAMP BY " however, due to out of order threshold and late arrival threshold, this can be different. 

You can select "System.Timestamp" as a column to confirm the behavior.

**Comment by mamccrea** [comment]
I hope this information is helpful. I will now close this thread. If you have any additional questions, please reopen this issue. 

#please-close

**Comment by mamccrea** [comment]
Hi @qusp66 - I will now proceed to close this thread. If this is still an issue for you, please reopen the issue. 

#please-close
