### ISSUE TITLE
Custom timestamp is not taken into account in blob path for Stream analytics

### ISSUE THREAD

**Issue by ErezBinyamin** [MicrosoftDocs/azure-reference-other#115]
Given a query that looks like this:

```
SELECT
    EventDate,
    *
INTO
    [datalakeoutput]
FROM
    [csvdata] TIMESTAMP BY EventDate
```

According to documentation, EventDate should now be used as timestamp. However, when storing data into blobstorage with this path:

```
sadata/Y={datetime:yyyy}/M={datetime:MM}/D={datetime:dd}
```

I seem to still get ingested time. In my case, ingested time means nothing and I need to use EventDate for the path. Is this possible? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0430c84c-99b9-2e29-513c-219fa31b06ce
* Version Independent ID: dc9755db-0c16-267d-091d-1b2991c43988
* Content: [TIMESTAMP BY (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/timestamp-by-azure-stream-analytics#feedback)
* Content Source: [stream-analytics-docs/timestamp-by-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/timestamp-by-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @ErezBinyamin! Do you get the desired timestamp when you test the query or when your blob output does not use a path?

**Comment by ErezBinyamin** [comment]
The blob always outputs the path as current date, even if the eventdate timestamp is 2-3 days prior. So I check it at output and I test it through Visual Studio.

**Comment by mamccrea** [comment]
The value of "System.Timestamp" is the used for blob output path. "System.Timestamp" is normally assigned using the value in "TIMESTAMP BY " however, due to out of order threshold and late arrival threshold, this can be different. 

You can select "System.Timestamp" as a column to confirm the behavior.

**Comment by ErezBinyamin** [comment]
When checking data in Visual Studio, test and EventDate should be equal, however results look like this: 
```
EventDate                   ;Test
2020-04-03T11:13:07.3670000Z;2020-04-09T02:16:15.5390000Z
2020-04-03T11:13:07.0460000Z;2020-04-09T02:16:15.5390000Z
2020-04-03T11:13:07.0460000Z;2020-04-09T02:16:15.5390000Z
2020-04-03T11:13:07.3670000Z;2020-04-09T02:16:15.5390000Z
2020-04-03T11:13:08.1470000Z;2020-04-09T02:16:15.5390000Z
```

Late tollerance arrival window is set as: 99:23:59:59 Out of order tollerance is set as: 00:00:00:00 with out of order action set to adjust.

When running same query in Stream Analytics on Azure i get this result:

```
[{"eventdate":"2020-04-03T11:13:20.1060000Z","test":"2020-04-03T11:13:20.1060000Z"},
{"eventdate":"2020-04-03T11:13:20.1060000Z","test":"2020-04-03T11:13:20.1060000Z"},
{"eventdate":"2020-04-03T11:13:20.1060000Z","test":"2020-04-03T11:13:20.1060000Z"}] 
```
So far so good. When running the query with data on Azure it produces this path: 
```
Y=2020/M=04/D=09
```
It should have produced this path: Y=2020/M=04/D=03 Interestingly enough, when checking the data that is actually stored in blobstorage I find this: 
```
EventDate,test
2020-04-03T11:20:39.3100000Z,2020-04-09T19:33:35.3870000Z,
```
System.timestamp seems to only be altered when testing the query on sampled data, but is not actually altered when the query is running normally and receiving data.

I have tested this with late arrival setting set to 0 and 20 days. In reality I need to disable late arrival adjustment as I might get events that are years old through the pipeline. 

I have checked and double checked and the system.timestamp property is altered when running query on Azure Portal, however it does not actually produce the correct path.

**Comment by ErezBinyamin** [comment]
Also I am receiving sensor data that can be up to 3 years old, this means i have to go outside late arrival threshold, or turn it off, which i am not sure is possible.

**Comment by mamccrea** [comment]
We are currently investigating why the result of the query isn't being used in the blob path.

The late arrival policy appears to be off. Maximum days for late arrival is 20, so if the policy is set to 99:23:59:59 (99 days). The adjustment could be causing a discrepancy in System.Timestamp. 

By definition of late arrival tolerance window, for each incoming event, Azure Stream Analytics compares the event time with the arrival time; if the event time is outside of the tolerance window, you can configure the system to either drop the event or adjust the event’s time to be within the tolerance.

Consider that after watermarks are generated, the service can potentially receive events with event time lower than the watermark. You can configure the service to either drop those events, or adjust the event’s time to the watermark value.

As a part of the adjustment, the event’s System.Timestamp is set to the new value, but the event time field itself is not changed. This adjustment is the only situation where an event’s System.Timestamp can be different from the value in the event time field, and may cause unexpected results to be generated.

For more information, please see [Understand time handling in Azure Stream Analytics](https://docs.microsoft.com/azure/stream-analytics/stream-analytics-time-handling#late-arriving-events).

Unfortunately, testing with sample data in Azure portal doesn't take policies into account at this time.

**Comment by mamccrea** [comment]
I hope this information has been helpful. I will now proceed to close this issue. If you have any further questions, please reopen the issue.

#please-close
