### ISSUE TITLE
Abillity to turn off late arrival window when using "timestamp by"

### ISSUE THREAD

**Issue by kristerkarto** [MicrosoftDocs/azure-reference-other#116]
There should be a way to turn off late arrival threshold when using timestamp by. Enforcing a strict late arrival threshold that is based on arrival time and comparing it to an altered event time means limitations on using Stream Analytics when processing older data. This is an issue when you are setting up systems and need to catch up to present time and also if you want to rerun data that is previously sent through pipeline. 

Late arrival and out of order data is not always an issue and hence thresholds like this should not be mandatory. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0430c84c-99b9-2e29-513c-219fa31b06ce
* Version Independent ID: dc9755db-0c16-267d-091d-1b2991c43988
* Content: [TIMESTAMP BY (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/timestamp-by-azure-stream-analytics)
* Content Source: [stream-analytics-docs/timestamp-by-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/timestamp-by-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @kristerkarto - thank you for this feedback. TIMESTAMP BY tells ASA what to use to establish the timeline. If you use TIMESTAMP BY EnqueuedTimeUTC or don't specify TIMESTAMP BY (in which case ASA uses enqueued time) then no event can ever be late and it late arrival part of the policy is ignored.

**Comment by mamccrea** [comment]
I hope this information has been helpful. I will now proceed to close this issue. If you have any further questions, please reopen the issue.

#please-close

**Comment by kristerkarto** [comment]
Hi

Yes, but I need to use TIMESTAMP BY in order to get System.timestamp
overridden in Path when sending events to blob storage. If not the path
information is useless and there is no way to specify more than one element
from the query in the path information either.

tor. 23. apr. 2020 kl. 17:55 skrev PRMerger19 <notifications@github.com>:
