### ISSUE TITLE
"Null values are ignored"

### ISSUE THREAD

**Issue by mikegoatly** [MicrosoftDocs/azure-reference-other#117]
The documentation states that "Null values are ignored" - it would be good to be precise about what the return value is if *all* the summed values are null - i.e. it's zero.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8a294f-5829-eefe-d1ce-c4fdf1e6cde2
* Version Independent ID: 68b04800-62d9-a4f3-37d9-ce3c696d6581
* Content: [SUM (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/sum-azure-stream-analytics)
* Content Source: [stream-analytics-docs/sum-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/sum-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by alexr** [comment]
@mikegoatly just to note that for SUM as well as most other aggregates, for all NULL values the result is also NULL. One exception is COUNT, which counts non-null values, thus returning 0 for all NULLs.

**Comment by mikegoatly** [comment]
Thanks @alexr - that would definitely make a good addition to the documentation 😁

**Comment by mamccrea** [comment]
Thanks! I've updated the docs. The changes should go live by next week.
