### ISSUE TITLE
GetMetadataPropertyValue does not work on IoTHub enrichments

### ISSUE THREAD

**Issue by lucarv** [MicrosoftDocs/azure-reference-other#127]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f18461c-e0bf-e7b4-f34c-5a632fb06f66
* Version Independent ID: b7e06d15-933e-f361-21dd-e4e2a9294669
* Content: [GetMetadataPropertyValue (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/getmetadatapropertyvalue)
* Content Source: [stream-analytics-docs/getmetadatapropertyvalue.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/getmetadatapropertyvalue.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @lucarv - can you please share more information about the issue you are having?

**Comment by mamccrea** [comment]
Hi @lucarv - I am going to close this issue for now. If you are still having problems, please reopen the issue.
