### ISSUE TITLE
Parquet missing from "Data Types Overview" page

### ISSUE THREAD

**Issue by ds-mark** [MicrosoftDocs/azure-reference-other#128]
It seems Parquet is not mentioned on the entire Data Types Overview page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593d33f2-cdb5-f4f0-87b7-65f2064684bc
* Version Independent ID: 4fd0c3d0-8cbd-d3e7-20d9-513450d4761a
* Content: [Data Types (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/data-types-azure-stream-analytics)
* Content Source: [stream-analytics-docs/data-types-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/data-types-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Thanks for bringing this to our attention, @ds-mark. We'll add it to the conversion types table.

**Comment by mamccrea** [comment]
@ds-mark - there is no datatype conversion necessary for Parquet, so we will not be updating the article. If I've misunderstood your concern, please let me know.

**Comment by mamccrea** [comment]
Hi @ds-mark. I am going to add a note to the doc stating that conversion isn't necessary for Parquet. If you have any other questions, please reopen the issue.

#please-close
