### ISSUE TITLE
Net# Link Not Working

### ISSUE THREAD

**Issue by lucazav** [MicrosoftDocs/azure-reference-other#130]
The [Guide to the Net# Neural Networks Specification Language](https://go.microsoft.com/fwlink/?LinkId=402867) link provided in the [Neural Network Regression](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/neural-network-regression.md) page is not working.

**Comment by lucazav** [comment]
I've just found the correct link:

https://docs.microsoft.com/en-us/azure/machine-learning/studio/azure-ml-netsharp-reference-guide

**Comment by mamccrea** [comment]
Thanks @lucazav 

@PeterCLu - it looks like this fwlink is pointing to the wrong target.

**Comment by j-martens** [comment]
Thanks for your report. It has now been fixed. #please-close
