### ISSUE TITLE
Please extend the create table sample to include a column that is of type record 

### ISSUE THREAD

**Issue by dave-read** [MicrosoftDocs/azure-reference-other#133]
[Enter feedback here]
The docs note that one of the data types is record.  The [data types docs](https://docs.microsoft.com/en-us/stream-analytics-query/data-types-azure-stream-analytics#supported-data-types) say:

```record	Set of name/value pairs. Values must be of supported data type.```

But there no example of the syntax for defining a column of type record.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65bb71d-9754-a514-0c65-b5e465fa6073
* Version Independent ID: e0d71449-2ea0-352d-c0e8-1070fd0726df
* Content: [CREATE TABLE (Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/create-table-stream-analytics)
* Content Source: [stream-analytics-docs/create-table-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/create-table-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @dave-read! The syntax for record is the same as defining the other columns.

`CREATE TABLE TollTagEntry (  
   TollId nvarchar(max),  
   TollRecord record,  
);`

**Comment by mamccrea** [comment]
I hope this information was helpful! If you have any additional questions, please reopen the issue.
