### ISSUE TITLE
Your WITH command needs an AS

### ISSUE THREAD

**Issue by ksaye** [MicrosoftDocs/azure-reference-other#134]
[Enter feedback here]

The last sample query 
```
WITH HoppingWindowResults 
(
```

should be
```
WITH HoppingWindowResults AS
(
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009afc26-6738-2a51-a360-cbc8eacdf0b4
* Version Independent ID: 06555bc8-bae5-3e41-b095-ea562e696efc
* Content: [Windows (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/windows-azure-stream-analytics)
* Content Source: [stream-analytics-docs/windows-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/windows-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @ksaye - thanks for bringing this to our attention. I'm updating the page right now. The changes should go live early next week.
