### ISSUE TITLE
Module issues

### ISSUE THREAD

**Issue by vyshaghin** [MicrosoftDocs/azure-reference-other#135]
How to connect connect the output of Tune Model Hyperparameters to the Untrained model input in Cross validate.
Output of Tune model is a Trained Model right?

**Comment by JasonWHowell** [comment]
I'm guessing this feedback is most likely related to https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/tune-model-hyperparameters

The author is listed as @xiaoharper 
CC: @cjgronlund 

#assign:xiaoharper

**Comment by PeterCLu** [comment]
Hi @vyshaghin, thanks for your question. You're correct, the output of the Tune Model Hyperparameters module is a trained model (Type ILearnerDotNet). You can verify this by hovering your mouse over the output node of the Tune Model Hyperparameters module.

![image](https://user-images.githubusercontent.com/10505176/99427398-3a2d2f80-28ba-11eb-8786-dd2e8afb3d10.png)

The above screenshot shows you a sample cross validation and hyperparameter sweep.

For Studio (classic), you can find information on performing hyperparameter sweeps with cross validation in the following article: https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/cross-validate-model#cross-validation-with-a-parameter-sweep

#please-close
