### ISSUE TITLE
The time axis in the diagram seems to be inconsistent with the formula - axis shown as Minutes but formula uses Second.

### ISSUE THREAD

**Issue by harrchen88** [MicrosoftDocs/azure-reference-other#139]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea19668-9e4e-ee61-e5ec-725746f0c6fc
* Version Independent ID: bac2197e-1698-6bc1-0282-d62154504bcc
* Content: [Sliding Window (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/sliding-window-azure-stream-analytics)
* Content Source: [stream-analytics-docs/sliding-window-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/sliding-window-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Thanks @harrchen88! I've updated the screenshot. The changes should go live tomorrow.

#please-close
