### ISSUE TITLE
Stream analytics query is ANSI SQL subset?

### ISSUE THREAD

**Issue by devudu** [MicrosoftDocs/azure-reference-other#143]
In the [document](https://docs.microsoft.com/en-us/stream-analytics-query/stream-analytics-query-language-reference) , first section's heading says "Stream Analytics Query Language, a subset of T-SQL syntax"

I think it would be more appropriate to say Stream analytics query language is a subset of ANSI SQL instead of T-SQL.  Because T-SQL is more specific for batch processing specific to MSSQL.

Regards,
Devender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c1bd60-1296-3916-576f-7e66406e7e88
* Version Independent ID: 98ce7ef9-48e6-001c-967f-0f0c204e3921
* Content: [Stream Analytics Query Language Reference - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/stream-analytics-query-language-reference)
* Content Source: [stream-analytics-docs/stream-analytics-query-language-reference.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/stream-analytics-query-language-reference.md)
* Service: **stream-analytics**
* GitHub Login: @JSeb225
* Microsoft Alias: **jeanb**

**Comment by JasonWHowell** [comment]
#assign:jseb225

**Comment by JSeb225** [comment]
Hi thanks for the feedback. Stream Analytics query language is actually derived from T-SQL (which itself extends ANSI SQL). As a result, SAQL inherits some of the syntax, behaviors and operators from T-SQL (e.g. TRY_CAST, String operators, Math operators), that are not available in ANSI SQL.

**Comment by JasonWHowell** [comment]
Hi @devudu 
Thanks for the question. Hope the reply above resolves the issue. Let us know if you need to continue the discussion.
Thanks, Jason
#please-close
