### ISSUE TITLE
Session can be used in what two way?

### ISSUE THREAD

**Issue by deomaximo** [MicrosoftDocs/azure-reference-other#144]
There's a note here that says it can be used in two ways but doesn't list them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1db0202-a8e1-acb0-a8e7-7858c53056f9
* Version Independent ID: 19cc9a90-12f1-236f-996e-19561ce1b181
* Content: [Session Window (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/session-window-azure-stream-analytics)
* Content Source: [stream-analytics-docs/session-window-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/session-window-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @JSeb225
* Microsoft Alias: **jeanb**

**Comment by JasonWHowell** [comment]
Hi @deomaximo 

I think the note means there are two syntax conventions possible as shown in the Syntax example. 

![image](https://user-images.githubusercontent.com/5067358/110363262-318e6f80-7ff7-11eb-8acc-f195c5fc92a3.png)

Does that help?
Thanks, Jason

**Comment by deomaximo** [comment]
Yes. Thanks!

**Comment by JasonWHowell** [comment]
#please-close
