### ISSUE TITLE
DECLARE, SET, sp_executesql ?

### ISSUE THREAD

**Issue by Krold** [MicrosoftDocs/azure-reference-other#145]
Does Azure Stream Analytics provides th use of DECLARE, SET and sp_executesql for building more complex queries?
I would like to programmatically define an WHERE clause. For instance: SELECT * FROM (' + @QueryText + @WhereText + ')'

**Comment by JasonWHowell** [comment]
Hi @Krold I don't think dynamic SQL is supported. 

It's more of a compiled language that is fixed once a Stream Analytics job begins.

There are suggestions online here use Case statements or Azure functions.
https://stackoverflow.com/questions/59860117/can-you-use-dynamic-run-time-outputs-with-azure-stream-analytics

**Comment by Krold** [comment]
Thanks @JasonWHowell

**Comment by JasonWHowell** [comment]
#please-close
