### ISSUE TITLE
Typo in "Basic example" code snippet

### ISSUE THREAD

**Issue by DiPal2** [MicrosoftDocs/azure-reference-other#149]
"Basic example" code snippet contains incorrect spelling for TIMESTAMP:
FROM TwitterStream TIMESTAM BY CreatedAt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e46c01-a724-6e06-ec87-38daab2eec98
* Version Independent ID: e3613fd3-b9f7-713c-0d60-f3338434c79b
* Content: [Snapshot Window (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/snapshot-window-azure-stream-analytics)
* Content Source: [stream-analytics-docs/snapshot-window-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/snapshot-window-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @JSeb225
* Microsoft Alias: **jeanb**

**Comment by JasonWHowell** [comment]
This was resolved by https://github.com/MicrosoftDocs/azure-reference-other/pull/147
Thanks for noticing the problem @DiPal2

**Comment by JasonWHowell** [comment]
#please-close
