### ISSUE TITLE
Incorrect Session Window Figure

### ISSUE THREAD

**Issue by karan-shell** [MicrosoftDocs/azure-reference-other#160]
Incorrect detail in Session window Figure on this page. Correct figure seems to be on page https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-window-functions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1db0202-a8e1-acb0-a8e7-7858c53056f9
* Version Independent ID: 19cc9a90-12f1-236f-996e-19561ce1b181
* Content: [Session Window (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/session-window-azure-stream-analytics)
* Content Source: [stream-analytics-docs/session-window-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/session-window-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @Fleid
* Microsoft Alias: **fleide**

**Comment by PandaXXY** [comment]
The session window figure still doesn't look correct.
