### ISSUE TITLE
Update to syntax section

### ISSUE THREAD

**Issue by BrandonWhite-Altius** [MicrosoftDocs/azure-reference-other#164]
The following is missing from the syntax section at the top of the page.
`| expression [ NOT ] IN ('expression','expression',...)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d95b977-1f78-9a1b-de56-e0d1cf4b1d40
* Version Independent ID: 98dd5dfe-631c-5ff5-c1ee-516d3c68a195
* Content: [WHERE (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/where-azure-stream-analytics)
* Content Source: [stream-analytics-docs/where-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/where-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @Fleid
* Microsoft Alias: **fleide**

**Comment by Fleid** [comment]
Good catch, thanks!
Fixing now.

**Comment by Fleid** [comment]
It took its time but it's online now :)
Thanks again!

#please-close
