### ISSUE TITLE
Log Table SynapseIntegrationActivityRuns - where to find ErrorMessages of my activity runs

### ISSUE THREAD

**Issue by mafis-hh** [MicrosoftDocs/azure-reference-other#166]
In the past I developed on ADF and used the corresponding ADF log table "[ADFActivityRun](https://github.com/MicrosoftDocs/azure-reference-other/blob/main/azure-monitor-ref/tables/adfactivityrun.md)" for monitoring the errors in our data pipelines.
I used especially the columns "ErrorMessage" and some other columns arround the error messages.

Now I've developded similar capabilities with Azure Synapse instead of ADF v2. 
I've identified for synapse the new log table called "[SynapseIntegrationActivityRuns](https://github.com/MicrosoftDocs/azure-reference-other/blob/main/azure-monitor-ref/tables/synapseintegrationactivityruns.md)".

But for the new synapse logging table I'm missing all the Error related columns. Are there other tables for synapse error messages? Or are the error messages completely missing in the log analytics workspaces?

I assume the benefit of these tables in Azure Log Analytics is to analyze the error codes and error messages, but therefore I need this information.
Can you please let me know where I can find it for synapse?

Thank you in advance.

**Comment by Fleid** [comment]
Hey @mafis-hh, I pinged the ADF/Synapse team internally, I'll let you know when I get an update.

**Comment by Fleid** [comment]
Hi @mafis-hh, I was able to confirm that this gap is on the radar of the ADF/Synapse team. Addressing it is on their roadmap, but no ETA yet.

I'll close this issue, please re-open it if need be. 
#please-close

**Comment by mafis-hh** [comment]
Hi @Fleid, super thank you for the information.
Just one question, where can I get a notification once this is available?

**Comment by Fleid** [comment]
Sadly I won't be able to track it, as it's not really in my scope.
But I'm sure they'll annouce it somehow.
