### ISSUE TITLE
Typo: Azure Service Bus Event Hub

### ISSUE THREAD

**Issue by mattmazzola** [MicrosoftDocs/azure-reference-other#169]
It looks like there is a typo in this line

> For the events from Azure Service Bus Event Hub, the arrival time is the timestamp given by the Event Hub

I think either the "Service Bus" text should be removed, or it should say "Azure Service Bus OR Event Hub", but as it is written it makes it sounds like one product but it's not. As I understand Service Bus is lower level and Event Hub is built on top of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c1bd60-1296-3916-576f-7e66406e7e88
* Version Independent ID: 98ce7ef9-48e6-001c-967f-0f0c204e3921
* Content: [Stream Analytics Query Language Reference - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/stream-analytics-query-language-reference)
* Content Source: [stream-analytics-docs/stream-analytics-query-language-reference.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/stream-analytics-query-language-reference.md)
* Service: **stream-analytics**
* GitHub Login: @Fleid
* Microsoft Alias: **fleide**

**Comment by Fleid** [comment]
I'm wondering if that wasn't the previous name of the service. Anyway it's a typo now, I'll fix it, thanks :)
