### ISSUE TITLE
Sample data would be helpful in understanding query syntax. 

### ISSUE THREAD

**Issue by DarinShapiroMS** [MicrosoftDocs/azure-reference-other#171]
Looking at the sample queries, it's hard to fully understand without seeing the sample data the query is based on. Is the sample data set somewhere else not linked to here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd5e7e60-64ee-62fa-27ba-8221aadbd58a
* Version Independent ID: 0ba9cfb9-7780-78da-01df-e2dc0b93bf9e
* Content: [MATCH_RECOGNIZE (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/match-recognize-stream-analytics)
* Content Source: [stream-analytics-docs/match-recognize-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/match-recognize-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @Fleid
* Microsoft Alias: **fleide**

**Comment by Fleid** [comment]
Good point. I plan to update the doc with more details, but not in the short term.
In the meantime, another example can be found here: https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-stream-analytics-query-patterns#advanced-pattern-matching-with-match_recognize

**Comment by Fleid** [comment]
Hey @DarinShapiroMS, I'm going to close that issue as I don't have an ETA to when the doc will be updated, and we have the other sample available.
Please open again if you feel strongly this should be tracked ;)
#please-close
