### ISSUE TITLE
IoT Hub message user properties are not arriving in ASA job?

### ISSUE THREAD

**Issue by sandervandevelde** [MicrosoftDocs/azure-reference-other#172]
According to the documentation, User properties and IoT Hub routing enrichments are supported by the IoT Hub.

    Additionally, twin properties and enriched properties added using IoT Hub message enrichment can also be retrieved using GetMetadataPropertyValue.

I tried to get a user property (together with some message enrichments).

I do not see them arriving in an Azure Stream Analytics job, listening to the IoT Hub:

![image](https://user-images.githubusercontent.com/694737/160900435-34a828b8-2a2e-4857-a5c3-8a620cf801d8.png)

I see them arriving in an Azure Function (just to check the EventData message) listing to the same IoT Hub messages:

![image](https://user-images.githubusercontent.com/694737/160900670-b326d02e-8ea8-4d78-b016-a4fa8e488486.png)

So, what am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f18461c-e0bf-e7b4-f34c-5a632fb06f66
* Version Independent ID: b7e06d15-933e-f361-21dd-e4e2a9294669
* Content: [GetMetadataPropertyValue (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/getmetadatapropertyvalue)
* Content Source: [stream-analytics-docs/getmetadatapropertyvalue.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/getmetadatapropertyvalue.md)
* Service: **stream-analytics**
* GitHub Login: @Fleid
* Microsoft Alias: **fleide**

**Comment by Fleid** [comment]
Hey @sandervandevelde!
That's an UI issue. Currently the portal query editor doesn't support `GetMetadataPropertyValue` (see the note [here](https://docs.microsoft.com/en-us/stream-analytics-query/getmetadatapropertyvalue#adapter-metadata-properties)).
If you check in VS Code it should work properly.

**Comment by sandervandevelde** [comment]
Ah, missed that one. 

I hope this is fixed at some point in time. For customer/community demonstrations and blogging, the portal is the preferred way to communicate/demonstrate features (simple to understand for newbies).

**Comment by sandervandevelde** [comment]
Closing this now. Thanks.

**Comment by Fleid** [comment]
> Ah, missed that one.
> 
> I hope this is fixed at some point in time. For customer/community demonstrations and blogging, the portal is the preferred way to communicate/demonstrate features (simple to understand for newbies).

We know, and be sure that we do want to close that gap.

**Comment by sandervandevelde** [comment]
If you want to have this tested, I'm happy to help ;-)
