### ISSUE TITLE
<> for UdpUse

### ISSUE THREAD

**Issue by mrkesu** [MicrosoftDocs/azure-reference-other#178]
UdpUse should be 0 or 1, but half of the results are <>, what does that mean? I have seen this in some of the other AVD diagnostic logs as well.

**Comment by JasonWHowell** [comment]
@mrkesu Sorry we are slow to respond. Do you remember which page you found the information on?

#assign:bwren

**Comment by JasonWHowell** [comment]
Maybe related to page https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/wvdconnections

**Comment by mrkesu** [comment]
Sorry for the slow response.

Yes, it is for WVDConnections 😄 I assumed the page I sent this feedback from had attached the context.

UdpUse logs whether the client is connected using TCP or UDP (UDP is used for RDP Shortpath).

"1" obviously means that UDP is being used, "0" means it is using TCP, but many clients log "<>" and there is no documentation that indicates what that means...

**Comment by rboucher** [comment]
#reassign:rboucher

**Comment by rboucher** [comment]
#reassign:Edb-MSFT

**Comment by EdB-MSFT** [comment]
Hi @mrkesu , Sorry for the delay in replying.
`UdpUse` is  an integer corresponding to whether the UDP protocol is used for the connection. 0=not used, 1= used, <> =null.
Note that there is an additional field,  `UdpType`  0 = NotUsed, 2 = ShortpathPublic, 4 = Relay.
I hope this helps.

**Comment by EdB-MSFT** [comment]
#please-close
