### ISSUE TITLE
Second example in the Examples section is missing the end '.  REPLACE(‘cdabcd’, ‘cd’, ‘x)

### ISSUE THREAD

**Issue by PaulFeaser** [MicrosoftDocs/azure-reference-other#184]
Second example in the Examples section is missing the end '.  REPLACE(‘cdabcd’, ‘cd’, ‘x)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3e91116-1a5b-14d4-c739-317fcfe618e8
* Version Independent ID: 5107eccc-6ef8-ea10-6364-cf7d8bcb651a
* Content: [REPLACE (Azure Stream Analytics) - Stream Analytics Query](https://learn.microsoft.com/en-us/stream-analytics-query/replace-azure-stream-analytics)
* Content Source: [stream-analytics-docs/replace-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/main/stream-analytics-docs/replace-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @Fleid
* Microsoft Alias: **fleide**

**Comment by JasonWHowell** [comment]
@PaulFeaser thanks for pointing out this issue. I'll fix it today.
