### ISSUE TITLE
Please provide a description

### ISSUE THREAD

**Issue by hoakedo** [MicrosoftDocs/azure-reference-other#185]
Please include a "description" whenever possible. I received a feedback from cx that there was not enough information.

https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/signinlogs

**Comment by vkyamaguchi** [comment]
Hi @bwren , @JasonWHowell 
any updates on this issue?
Description is still hardly mentioned.

**Comment by JasonWHowell** [comment]
I think these pages are automated docs, so we can't edit the pages directly and have to rely on the development team upstream to improve the text. @bwren may have a relationship with them.

**Comment by rboucher** [comment]
#reassign:EdB-MSFT

**Comment by EdB-MSFT** [comment]
tracking internally
#please-close
