### ISSUE TITLE
Please update with detailed descriptions with information about the services that utilize the columns

### ISSUE THREAD

**Issue by roger-wallace-MS** [MicrosoftDocs/azure-reference-other#203]
I have a customer who has need to monitor the IP addresses that connect through their AFD profile. The problem is that there are two columns in this table that can populate with the IP addresses of AFD connections where the difference is one capitalizated letter (clientIp_s vs. clientIP_s). 

This caused the customer to believe that there was a platform issue with IP addresses not being populated when they were just split between the two columns. There are also several different columns that are used by other services that can also hold IP addresses which can lead to confusion about which column is the correct on to use, not to mention the other columns that aren't given descriptions that aren't obvious in where/how they are used.

**Comment by JasonWHowell** [comment]
Could be related to this page. I'm not entirely sure. 
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/azurediagnostics

**Comment by roger-wallace-MS** [comment]
@JasonWHowell Yes that is the same page. I got to this page by clicking the pencil in the top right of the documentation

**Comment by rboucher** [comment]
When items are in AzureDiagnostics, this is one of the risks. It's used by multiple services.  Is there anything else to do on this issue?  When a resource provider onboards to the newer system they they get dedicated tables for just them. That's the direction we are moving in. AzureDiagnostics will be hopefully be used less and less over time.

**Comment by rboucher** [comment]
#reassign:robb

**Comment by rboucher** [comment]
#reassign:rboucher

**Comment by jikuja** [comment]
I've been collecting links to documentation that describes `AzureDiagnostics` table schema extensions: https://gist.github.com/jikuja/530042a78cf843e22f0f954a7fe43831 for own use.

Similar list should be on https://github.com/MicrosoftDocs/azure-reference-other/blob/main/azure-monitor-ref/tables/azurediagnostics.md#azure-diagnostics-mode

In this case `Front Doors` probably should link to https://learn.microsoft.com/en-us/azure/frontdoor/front-door-diagnostics?pivots=front-door-standard-premium#logs. Providing those links should make easier to find field descriptions while waiting for all remaining services to use service-specific tables.

**Comment by ajetasin** [comment]
#sign-off

**Comment by rboucher** [comment]
#reassign:EdB-MSFT

**Comment by rboucher** [comment]
Ed, sending to you as you maintain the references, but a bigger discussion to see how we could automate this linking.

**Comment by rboucher** [comment]
#reassign:rboucher

**Comment by rboucher** [comment]
I'm going to close this issue for now. I have a bigger project going trying to document all the table mappings of resource logs to Azure Monitor Logs/Log Analytics tables.  However, if you have resources out there that show a field to field, mapping let me know on this Github issue. AzureDiagnostics is a "dying table" in that all new services do not use it. They get dedicated tables precisely for the reason listed in this issue. As older services onboard to the new tables, it's best to use those. If you want the older services to onboard to them, please comment here and I can pass on the information.

**Comment by rboucher** [comment]
#please-close
