### ISSUE TITLE
Some columns do not have a description, so please include it.

### ISSUE THREAD

**Issue by vkyamaguchi** [MicrosoftDocs/azure-reference-other#206]
Some columns do not have a description, so please include it.
![image](https://user-images.githubusercontent.com/124872654/226246427-eac22186-77f9-4f14-a25c-29ed812bd419.png)
![image](https://user-images.githubusercontent.com/124872654/226246442-bb3aaaaa-b4ff-4400-ba50-5824994503d0.png)

**Comment by JasonWHowell** [comment]
We aren't sure which page this feedback is related to. 

Each kind of monitoring agent will have different entries potentially, and there are hundreds of kinds, so the answer could be that "it varies".

See the chart here for more detail on Windows Events for example: 
https://learn.microsoft.com/en-us/azure/azure-monitor/agents/data-sources-windows-events

And Azure services
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/AzureMetrics#columns

etc.

**Comment by EdB-MSFT** [comment]
Thanks for your feedback. We are aware of this issue and are working to get the descriptions populated.
#please-close
