### ISSUE TITLE
StackTrace incomplete

### ISSUE THREAD

**Issue by PandaFoxx** [MicrosoftDocs/azure-reference-other#220]
Using Azure Log Analytics Workspace and KQL analysing AppServiceAppLogs.

From what I can see the stacktrace only shows one line of an error. 

EG. "Object reference not set to an instance of an object"

How can I expand this to see the full stacktrace detail? So I can see what file and line the error occured..

**Comment by EdB-MSFT** [comment]
#assing @guywi-ms

**Comment by guywi-ms** [comment]
@PandaFoxx thanks for reaching out and apologies for the delayed response.
There are various ways to query monitoring data collected to your Log Analytics workspace - for example, in the portal or querying using the API. If you are using these methods, but the error information in your Log Analytics workspace is incomplete, please [open a support case](https://azure.microsoft.com/en-us/support/create-ticket/).

#please-close
