### ISSUE TITLE
Wrong note on DATEDIFF for JOIN in Azure Stream Analytics SQL documentation

### ISSUE THREAD

**Issue by ste-camp** [MicrosoftDocs/azure-reference-other#245]
In the section "Special DATEDIFF Function for JOIN" the last paragraph about Return Type says:

> The returned value can be negative if the timestamp of second input_source is greater than the first.

but this is opposite to the normal working of the DATEDIFF function that returns a negative value when the FIRST argument is greater than the second.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33ef43ed-597c-56f3-7cb6-f42e0b7ea288
* Version Independent ID: 59b37583-46a8-2cf7-495a-e4731af83aa0
* Content: [JOIN (Azure Stream Analytics) - Stream Analytics Query](https://learn.microsoft.com/en-us/stream-analytics-query/join-azure-stream-analytics)
* Content Source: [stream-analytics-docs/join-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/main/stream-analytics-docs/join-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @ajetasin
* Microsoft Alias: **ajetasi**

**Comment by ajetasin** [comment]
#sign-off

**Comment by spelluru** [comment]
@ajetasin - For a GitHub issue (not a PR), we need to enter `#please-close` to close the issue. Thanks.

#please-close

**Comment by ajetasin** [comment]
#please-close
