### ISSUE TITLE
problems with percentile_cont and percentile_disc

### ISSUE THREAD

**Issue by rumani-gabriel** [MicrosoftDocs/azure-reference-other#250]
I have a problem, I'll give a code for example case:

[Enter feedback here]

ELECT
    installationFullName, PERCENTILE_CONT(0.95) OVER (ORDER BY Real_tanque) as mediana
    FROM [autonomia]  
    GROUP BY installationFullName,SlidingWindow(hour, 1)

and this is the error in the console:

Failed to compile the query script: Parameter '0' of function 'percentile_cont' is out of range between '0' and '1' : '95'.. Error position: {"StartLine":84,"StartColumn":27,"StartOffset":2091,"EndLine":84,"EndColumn":75,"EndOffset":2139,"Expression":"PERCENTILE_CONT ( 0.95 ) OVER ( ORDER BY Real_tanque )"}.
[2023/08/30 04:10:47 PM] [Error] An error occurred while executing the command: localrun, error details: Parameter '0' of function 'percentile_cont' is out of range between '0' and '1' : '95'..

I don't understand why it doesn't work
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50141507-37cc-1180-1e02-2b737a7c7cad
* Version Independent ID: 881c9624-2a77-4a7e-801e-8c6f2ef294d3
* Content: [Percentile_Cont (Azure Stream Analytics) - Stream Analytics Query](https://learn.microsoft.com/en-us/stream-analytics-query/percentile-cont-azure-stream-analytics)
* Content Source: [stream-analytics-docs/percentile-cont-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/main/stream-analytics-docs/percentile-cont-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @ajetasin
* Microsoft Alias: **ajetasi**

**Comment by ajetasin** [comment]
#sign-off

**Comment by spelluru** [comment]
#please-close
