### ISSUE TITLE
Can GetArrayElement cope with an UDF returning an array?

### ISSUE THREAD

**Issue by sandervandevelde** [MicrosoftDocs/azure-reference-other#258]
The array expression could be:

> Is the array expression to be evaluated as a source array. array_expression can be a column of type Array or result of another function call.

Is it possible to feed the GetArrayElements function the outcome of a UDF function? 

If so, please add it to the documentation, if not add a warning in the documentation.

See also this [MS Learn question](https://learn.microsoft.com/en-us/answers/questions/1373844/is-there-anything-else-to-pay-attention-to-when-us?orderby=helpful) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7c13fec-819d-6b04-603b-ac9b4a3fc72f
* Version Independent ID: 0420f6c5-e363-c41d-bb80-0231eb4dd7e2
* Content: [GetArrayElement (Azure Stream Analytics) - Stream Analytics Query](https://learn.microsoft.com/en-us/stream-analytics-query/getarrayelement-azure-stream-analytics)
* Content Source: [stream-analytics-docs/getarrayelement-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/main/stream-analytics-docs/getarrayelement-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @ajetasin
* Microsoft Alias: **ajetasi**

**Comment by ajetasin** [comment]
#sign-off

**Comment by spelluru** [comment]
#please-close

**Comment by spelluru** [comment]
#reopen

**Comment by spelluru** [comment]
@ajetasin - Could you reopen and reply to the comment? Thanks.
