### ISSUE TITLE
Wrong column description about ACSEmailStatusUpdateOperational.DeliveryStatus

### ISSUE THREAD

**Issue by georgeOsdDev** [MicrosoftDocs/azure-reference-other#269]
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/acsemailstatusupdateoperational
<img width="425" alt="image" src="https://github.com/MicrosoftDocs/azure-reference-other/assets/1381907/92d52203-7a2d-4b3c-9051-73917f58f8d5">

I think the description `The count of unique recipients on the Cc line.`  is description of `CcRecipientsCount`

**Comment by rboucher** [comment]
#assign:rboucher

**Comment by rboucher** [comment]
Thanks @georgeOsdDev.  Checking on this.

**Comment by EdB-MSFT** [comment]
Hi @georgeOsdDev. We have opened a work item to fix this. It should be done soon.

**Comment by EdB-MSFT** [comment]
#please-close
