### ISSUE TITLE
Load balancer doesn't support Resource or Diagnostic logs

### ISSUE THREAD

**Issue by kri1603** [MicrosoftDocs/azure-reference-other#275]
We currently don't support Load balancer Resource or Diagnostic logs. 
https://learn.microsoft.com/en-us/azure/load-balancer/monitor-load-balancer-reference#resource-logs

These logs "LoadBalancerAlertEvent" and "LoadBalancerHealthProbeStatus" aren't supported in Load balancer via LB Diagnostic Logs or via Azure Monitor.

Hence, this doc: https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-logs/microsoft-network-loadbalancers-logs needs to be corrected.

**Comment by EdB-MSFT** [comment]
Hi @kri1603. Thanks for pointing this out. I've opened an internal work item to correct this.
Closing this issue.

#please-close

**Comment by kri1603** [comment]
[like]  Kritika . reacted to your message:
________________________________
