### ISSUE TITLE
Link to paper is dead (Online Learning for Latent Dirichlet Allocation)

### ISSUE THREAD

**Issue by lukassvec** [MicrosoftDocs/azure-reference-other#67]
The link to https://machinelearning.wustl.edu/mlpapers/paper_files/NIPS2010_1291.pdf is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d36de66-8e65-5aae-0c1e-6011b0728d5b
* Version Independent ID: 828d278e-3bff-bfe6-8888-7ffa10477ef0
* Content: [Latent Dirichlet Allocation - Azure Machine Learning Studio](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/latent-dirichlet-allocation#feedback)
* Content Source: [studio-module-reference/latent-dirichlet-allocation.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/latent-dirichlet-allocation.md)
* Service: **machine-learning**
* GitHub Login: @ericlicoding
* Microsoft Alias: **amlstudiodocs**

**Comment by PeterCLu** [comment]
Thanks for the catch. In progress.

**Comment by PeterCLu** [comment]
Resolved

**Comment by PeterCLu** [comment]
#please-close

**Comment by lukassvec** [comment]
Thanks! Looks good.
