### ISSUE TITLE
Reference link no longer working

### ISSUE THREAD

**Issue by dulems** [MicrosoftDocs/azure-reference-other#70]
Hi,

The below link no longer works. Is there a copy of the blog post in a different location? Thank you!

https://blogs.technet.microsoft.com/machinelearning/2014/11/05/anomaly-detection-using-machine-learning-to-detect-abnormalities-in-time-series-data/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9eaa229-66a5-7ef5-73d1-f6bc81a3cec9
* Version Independent ID: 4cd5835e-e790-bda7-9c0b-864805572161
* Content: [Time Series Anomaly Detection - Azure Machine Learning Studio](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/time-series-anomaly-detection#feedback)
* Content Source: [studio-module-reference/time-series-anomaly-detection.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/time-series-anomaly-detection.md)
* Service: **machine-learning**
* Sub-service: **studio**
* GitHub Login: @xiaoharper
* Microsoft Alias: **amlstudiodocs**

**Comment by j-martens** [comment]
Thanks for letting us know. I could not find the article anymore so I've removed the link. Thanks for reporting, @dulems #please-close

**Comment by dulems** [comment]
Thanks, @j-martens!
