### ISSUE TITLE
Retrain a model estimated in "execute R script"?

### ISSUE THREAD

**Issue by tomwwagstaff-product** [MicrosoftDocs/azure-reference-other#73]
I have an experiment which estimates a model in "execute R script". Will it be possible to set up a retraining web service for this, or is this only possible using the native "Train model" module?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbb8db52-b798-17f9-3c1d-0fb3ae7cdead
* Version Independent ID: 57e87e2f-ac32-244e-53f2-50135d598d13
* Content: [Execute R Script - Azure Machine Learning Studio](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/execute-r-script#bkmk_RCodeSamples)
* Content Source: [studio-module-reference/execute-r-script.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/execute-r-script.md)
* Service: **machine-learning**
* Sub-service: **studio**
* GitHub Login: @xiaoharper
* Microsoft Alias: **amlstudiodocs**

**Comment by tomwwagstaff-product** [comment]
It's okay I think I've got it - not this way but via the Create R Model module, right? Sorry I don't see how to delete my question...

**Comment by j-martens** [comment]
Hi @tomwwagstaff-product, you can just close the issue. :-)
