### ISSUE TITLE
Algorithm used

### ISSUE THREAD

**Issue by KunalBasnet** [MicrosoftDocs/azure-reference-other#74]
What neural network algorithm is used here?
Feedforward neural network, CNN, Radial basis function, RNN... etc ?(or some other )
Which one is used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21be048d-33f7-901d-e6bc-c103f36843f3
* Version Independent ID: 4e492fae-14ac-5395-2e13-3b57d7ac0d74
* Content: [Neural Network Regression - Azure Machine Learning Studio](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/neural-network-regression#feedback)
* Content Source: [studio-module-reference/neural-network-regression.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/neural-network-regression.md)
* Service: **machine-learning**
* Sub-service: **studio**
* GitHub Login: @xiaoharper
* Microsoft Alias: **amlstudiodocs**

**Comment by xiaoharper** [comment]
@KunalBasnet  Feedforward is used here.

**Comment by KunalBasnet** [comment]
@xiaoharper
Any reference where i can see this working.?

**Comment by xiaoharper** [comment]
please refer to this https://github.com/dotnet/machinelearning

**Comment by KunalBasnet** [comment]
Thanks for that

**Comment by KunalBasnet** [comment]
@xioharper is it possible to run my self coded python model to run as webservice for prediction inside Azure ML? And if possible be help me with the references.

**Comment by j-martens** [comment]
@KunalBasnet - the doc issue itself has been resolved. For faster product support, I recommend the user forum. 
Check out these support resources:

Technical support for Azure Customers: Submit and manage support requests through the Azure portal.  https://docs.microsoft.com/azure/azure-supportability/how-to-create-azure-support-request

User forum: Ask questions, answer questions, and connect with other users in the Azure Machine Learning Studio support forum on MSDN. https://aka.ms/aml-forum-studio

#please-close
