### ISSUE TITLE
Algorithm for time series prediction

### ISSUE THREAD

**Issue by KunalBasnet** [MicrosoftDocs/azure-reference-other#76]
Is there any particular module for time series analysis and predicting the values?

And if not than which module of Azure ml is good to use for time series analysis? Suggest me one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 348ecdc8-3c47-5d70-e534-1caf121a39b2
* Version Independent ID: e607c6bf-fe83-e36a-eb9d-ff2934295df8
* Content: [Time Series - Azure Machine Learning Studio](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/time-series)
* Content Source: [studio-module-reference/time-series.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/time-series.md)
* Service: **machine-learning**
* Sub-service: **studio**
* GitHub Login: @xiaoharper
* Microsoft Alias: **amlstudiodocs**

**Comment by xiaoharper** [comment]
Hi @KunalBasnet,  the only pre-builtin time series module in Studio is **Time Series Anomaly Detection.**  You probably need to bring your own time series model with **Execute Customer Python/R Script Module**

**Comment by JasonWHowell** [comment]
Closing this out since the question has been answered. Please let us know if further assistance is needed. ~Jason
