### ISSUE TITLE
Can't update data to retrain model

### ISSUE THREAD

**Issue by tomwwagstaff-product** [MicrosoftDocs/azure-reference-other#78]
I want to create a pair of experiments, where the first experiment takes a new input and exports the result to blob storage, and the second experiment imports that result from blob storage to make its final prediction. I want to be able to retrain those experiments by changing the input to the first experiment. I've concluded from reading this that this is *not* possible - there is no way to get the second experiment to retrain in response to changes in the dataset stored in the blob. Is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ea8ea2-d21b-827e-9b48-2cf201905d77
* Version Independent ID: eb2e4712-bd00-ec3f-6f8f-c0c2ded8a990
* Content: [Import from Azure Blob Storage - Azure Machine Learning Studio](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/import-from-azure-blob-storage)
* Content Source: [studio-module-reference/import-from-azure-blob-storage.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/import-from-azure-blob-storage.md)
* Service: **machine-learning**
* Sub-service: **studio**
* GitHub Login: @xiaoharper
* Microsoft Alias: **amlstudiodocs**

**Comment by j-martens** [comment]
@xiaoharper - Harper, can you confirm this is or isn't possible for Tom? Thanks.

**Comment by xiaoharper** [comment]
Hi @tomwwagstaff-product, you are correct, it's not possible.

**Comment by JasonWHowell** [comment]
Closing this out since the question has been answered. Please let us know if further assistance is needed. ~Jason
