### ISSUE TITLE
opencv-python and imutils modules for Azure Functions in Linux environment using python

### ISSUE THREAD

**Issue by DaQin9356** [MicrosoftDocs/azure-reference-other#79]
Hi, I just would like to know how can I use opencv-python and imutils in Azure Functions, my code works pretty well in my local machine with VS code, but fails on Azure Functions in the cloud. 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: eb132516-c1b3-c97e-20f8-3295a126ab7a
* Version Independent ID: ee583f88-5055-a232-2b58-41d76082356f
* Content: [OpenCV Library Modules - Azure Machine Learning Studio](https://docs.microsoft.com/zh-cn/azure/machine-learning/studio-module-reference/opencv-library-modules#feedback)
* Content Source: [studio-module-reference/opencv-library-modules.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/opencv-library-modules.md)
* Service: **machine-learning**
* Sub-service: **studio**
* GitHub Login: @xiaoharper
* Microsoft Alias: **amlstudiodocs**

**Comment by xiaoharper** [comment]
Hi @DaQin9356  One possible reason is that the dependency package is not pre-installed. Check https://docs.microsoft.com/zh-cn/azure/machine-learning/studio-module-reference/execute-python-script on how to include new package. If you still have question, please reach out to amlforum@microsoft.com with your detailed error message.

**Comment by JasonWHowell** [comment]
Hi @DaQin9356 I hope Xiao's answer helped you. 
Since its been many months, I'll close this out. Please let us know if you need further assistance. Thanks, Jason
