### ISSUE TITLE
What data types can be input to a Train Model module?

### ISSUE THREAD

**Issue by tomwwagstaff-product** [MicrosoftDocs/azure-reference-other#80]
I'd like to clarify what type of object can be used as the input to a `Train Model` module.

Based on what I've read [here](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/train-model#expected-inputs) I think the answer is that this can only be a flat structure - which will be converted to a .NET DataTable in the background.

I don't think this can be a .NET DataSet containing several tables, can it?

**Comment by xiaoharper** [comment]
Hi @tomwwagstaff-product , your understanding is correct.  Only flat structure can be used.
