### ISSUE TITLE
PARTITION BY doesn't seem to be supported

### ISSUE THREAD

**Issue by codehoundltd** [MicrosoftDocs/azure-reference-other#84]
Currently, if I try and use the PARTITION BY condition in the MATCH_RECOGNIZE clause then the query is flagged as having an error and can not be executed. The same query with the PARTITION BY clause commented out will run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd5e7e60-64ee-62fa-27ba-8221aadbd58a
* Version Independent ID: 0ba9cfb9-7780-78da-01df-e2dc0b93bf9e
* Content: [MATCH_RECOGNIZE (Azure Stream Analytics - Preview) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/match-recognize-stream-analytics#feedback)
* Content Source: [stream-analytics-docs/match-recognize-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/match-recognize-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @codehoundltd! PARTITION BY is not currently supported with MATCH_RECOGNIZE. I will update the documentation accordingly.

**Comment by mamccrea** [comment]
#sign-off

**Comment by mamccrea** [comment]
#please-close
