### ISSUE TITLE
Function 'timestamp' is either not supported or not usable in this context

### ISSUE THREAD

**Issue by samerdokas** [MicrosoftDocs/azure-reference-other#85]
Any attempt to use the `System.Timestamp()` seems to result in an error. The example below is taken from the first example:
```
SELECT System.Timestamp() t   
FROM input   
TIMESTAMP BY MyTimeField
```
Result:
```
(ASACompilerTarget target) -&gt;
  Script.asaql(1,7,1,24): error : Function 'timestamp' is either not supported or not usable in this context. User defined function calls must start with "udf." prefix. Aggregate functions must be used together with a GROUP BY clause.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0431f918-6070-e736-4490-f6ac93bc9cfe
* Version Independent ID: e86bcac6-3775-6c2e-99bf-99f152508a9c
* Content: [System.Timestamp()  (Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/system-timestamp-stream-analytics?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fstream-analytics%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#feedback)
* Content Source: [stream-analytics-docs/system-timestamp-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/system-timestamp-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by samerdokas** [comment]
The same via `tools\SA.exe`:

```
2019-09-02 09:40:06 : Info : Create output folder .\saBuild.
2019-09-02 09:40:07 : Warning : Ignore js function file test.js.json as failed to find function code
2019-09-02 09:40:07 : Info : Begin to compile script ....
2019-09-02 09:40:08 : Error : Function 'timestamp' is either not supported or not usable in this context. User defined function calls must start with "udf." prefix. Aggregate functions must be used together with a GROUP BY clause.
```

**Comment by samerdokas** [comment]
However, using the undocumented version 2.0.0 of StreamAnalytics CICD component, it no longer complains about `timestamp`. Closing as it is apparently fixed.

**Comment by JasonWHowell** [comment]
@samerdokas nice find!
