### ISSUE TITLE
The documentation is a bit poor

### ISSUE THREAD

**Issue by abelunibo** [MicrosoftDocs/azure-reference-other#86]
-It doesn't clarify how the distance is calculated, whether is a simplistic Euclidean distance, or if it considers the earth surface curvature by using the Haversine formula.
-the input example refers to car2input and warehouse indistinctly, it should be one or the other. 
-In genera, I miss the classic "Remarks" section 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4aeaa3-f622-23d1-f475-f026c8699f47
* Version Independent ID: 270bfdd1-211e-4023-be54-d7041882bf21
* Content: [ST_DISTANCE (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-gb/stream-analytics-query/st-distance#feedback)
* Content Source: [stream-analytics-docs/st-distance.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/st-distance.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @abelunibo - thank you for the feedback! I will make fix the example and make a note about the formula. 

ST_DISTANCE calculates geodesic distance for all compatibility versions of ASA. The result varies a bit between ASA < 1.2 (SQL library) and ASA >= 1.2 (NTS library) as library changes, but it is insignificant when calculating geo distances. Cartesian distances require projection calculations and are not supported right now but they can be implemented on UDF.

**Comment by mamccrea** [comment]
#please-close
