### ISSUE TITLE
ordinal regression in ML.NET

### ISSUE THREAD

**Issue by intui** [MicrosoftDocs/azure-reference-other#90]
The page [ordinal-regression.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/ordinal-regression.md) describes the ordinal regression module. Is there a way to use this module/class in ML.NET in C#?
Any hints are welcome.
Greetings, Wido

**Comment by JasonWHowell** [comment]
@j-martens can you please help find someone to answer this question. Thanks! Jason

**Comment by j-martens** [comment]
@natke - can you comment?

**Comment by natke** [comment]
I'll move this over to the ML.NET repo.

**Comment by natke** [comment]
New issue created here: https://github.com/dotnet/machinelearning/issues/4947. This one can be closed, thank you.
