### ISSUE TITLE
Using GeoSpatial Functions (Azure Stream Analytics) on Big data

### ISSUE THREAD

**Issue by IscaAy** [MicrosoftDocs/azure-reference-other#91]
This tool is amazing for geospatial analysis. However, can I do batch processing, with big data, where my data is in terabytes and close to 1 Petabyte?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8013b7-8a17-dbf4-c882-15765c4f1498
* Version Independent ID: 336206c1-5700-8809-2f9d-205986656403
* Content: [GeoSpatial Functions (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/geospatial-functions#feedback)
* Content Source: [stream-analytics-docs/geospatial-functions.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/geospatial-functions.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @IscaAy - I apologize for the delayed response. You can perform batch processing by choosing blob input.

**Comment by mamccrea** [comment]
#please-close
