### ISSUE TITLE
Please expand example

### ISSUE THREAD

**Issue by hugovoerman** [MicrosoftDocs/azure-reference-other#94]
Hi,

Please expand this example. Including the reference file itself in CVS and JSON format. I can't find a sample for a JSON reference anywhere, so this might be a good place to create a complete example.

Thanks in advance,

Hugo Voerman

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64494cba-b4ee-4baf-6058-a533565c7e6b
* Version Independent ID: 70f7ee5c-4880-9f38-e53f-0b731069e7a9
* Content: [Reference Data JOIN (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/reference-data-join-azure-stream-analytics#feedback)
* Content Source: [stream-analytics-docs/reference-data-join-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/reference-data-join-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @hugovoerman - Thanks for providing feedback. I just wanted to make sure I understand your request. Are you asking for an example of reference input? Here's an [article on how to parse different formats](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-parsing-json), including JSON.

**Comment by hugovoerman** [comment]
Hi Mary,

I would like to see a complete example of streaming data including json reference data. So the payload of a streaming input, the contents of the reference json, how to put the reference data in a blob (with and without {date} and/or {hh}) , the sa query, and all else I forgot.

I have not been successful in making it work with reference data in blob. Using sql as reference source however was easy. But I want the refdata in blob, so please help with a complete example

Thanks in advance,

Hugo Voerman

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by mamccrea** [comment]
Hi @hugovoerman. Please see [Build an IoT solution by using Stream Analytics](https://docs.microsoft.com/azure/stream-analytics/stream-analytics-build-an-iot-solution-using-stream-analytics) for an example using reference data.

**Comment by mamccrea** [comment]
I will now proceed to close this thread. If you have any additional questions, please reopen this issue.

#please-close
