### ISSUE TITLE
Typo in first paragraph

### ISSUE THREAD

**Issue by toastermagic** [MicrosoftDocs/azure-reference-other#95]
"mapped into 5-second tumbling windows" - the diagram shows a 10-second window

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7481e5ce-9b20-2edb-4d3c-d73858d1dde8
* Version Independent ID: ff6f279d-6469-012a-1e4b-88b6f1830b8e
* Content: [Tumbling Window (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/tumbling-window-azure-stream-analytics#feedback)
* Content Source: [stream-analytics-docs/tumbling-window-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/tumbling-window-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Thanks for pointing that out @toastermagic. I've fixed the typo.

**Comment by mamccrea** [comment]
#please-close
