### ISSUE TITLE
Multi-table 

### ISSUE THREAD

**Issue by PandoraDirge** [MicrosoftDocs/azure-reference-other#97]
Is it possible to make multi-table from queries? 
Without the join clausure, i mean. 
Ex:
SELECT  A.*, B.Column1
FROM tableA  A, tableB B, tableC C
WHERE...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc04dea-6173-3db3-870d-ee0a0299355e
* Version Independent ID: 1017b911-c7d2-3c90-a5a7-23cb496f01c3
* Content: [FROM (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/from-azure-stream-analytics#feedback)
* Content Source: [stream-analytics-docs/from-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/from-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by mamccrea** [comment]
Hi @PandoraDirge - I apologize for the delayed response. This syntax (FROM a,b,c…) is not supported. We do support CROSS JOIN, but only for joining with reference data, because otherwise, you must provide temporal bounds for any sort of correlation (join)

**Comment by JasonWHowell** [comment]
@PandoraDirge it looks like Mary has provided a thoughtful answer. Please let us know if you need anything else. I'll close the thread assuming its resolved, but happy to continue if you need further clarification. Thanks~ Jason
